### ISSUE TITLE
How to configure plugin to use different output path

### ISSUE THREAD

**Issue by sashaepstein** [JakeWharton/twirl-maven-plugin#15]
My project's default output directory includes Scala compiler version part, i.e .../target/scala-2.12/
How to tell the plugin to use generated-sources folder in my output directory rather than default ../target/generated-sources? 
I do specify the output path in the build section of pom.xml in the outputDirectory element,
but plugin seems to ignore it.

**Comment by JakeWharton** [comment]
You can use the `outputDirectory` property of the plugin configuration:
https://github.com/JakeWharton/twirl-maven-plugin/blob/master/twirl-maven-plugin/src/main/java/com/jakewharton/twirl/CompileMojo.java#L52-L54

```xml
<plugin>
  <groupId>com.jakewharton.twirl</groupId>
  <artifactId>twirl-maven-plugin</artifactId>
  <version>1.2.0</version>
  <configuration>
    <outputDirectory>VALUE</outputDirectory>
  </configuration>
</plugin>
```
